version: "3.5"

networks:
  drone-network:
    driver: bridge

services:
  api:
    build:
      context: ../
      dockerfile: DroneDelivery.Api/Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "5000:80"
    networks:
      - drone-network
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    restart: on-failure
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=pass123!"
    ports:
      - "1401:1433"
    networks:
      - drone-network
